export let cartelera = [
    {
        "Title": "Avengers: Endgame",
        "Year": "2019",
        "Rated": "PG-13",
        "Released": "26 Apr 2019",
        "Runtime": "181 min",
        "Genre": "Action, Adventure, Drama",
        "Director": "Anthony Russo, Joe Russo",
        "Writer": "Christopher Markus, Stephen McFeely, Stan Lee",
        "Actors": "Robert Downey Jr., Chris Evans, Mark Ruffalo",
        "Plot": "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos's actions and undo the chaos to the universe, no matter what consequences may be in store, and no matter who they face...",
        "Language": "English, Japanese, Xhosa, German",
        "Country": "United States",
        "Awards": "Nominated for 1 Oscar. 70 wins &amp; 123 nominations total",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "8.4/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "94%"
        }, {"Source": "Metacritic", "Value": "78/100"}],
        "Metascore": "78",
        "imdbRating": "8.4",
        "imdbVotes": "948,888",
        "imdbID": "tt4154796",
        "Type": "movie",
        "DVD": "30 Jul 2019",
        "BoxOffice": "$858,373,000",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    },
    {
        "Title": "Harry Potter and the Deathly Hallows: Part 2",
        "Year": "2011",
        "Rated": "PG-13",
        "Released": "15 Jul 2011",
        "Runtime": "130 min",
        "Genre": "Adventure, Fantasy, Mystery",
        "Director": "David Yates",
        "Writer": "Steve Kloves, J.K. Rowling",
        "Actors": "Daniel Radcliffe, Emma Watson, Rupert Grint",
        "Plot": "Harry (Daniel Radcliffe), Ron (Rupert Grint), and Hermione (Emma Watson) continue their quest of finding and destroying Voldemort's (Ralph Fiennes') three remaining Horcruxes, the magical items responsible for his immortality. But as the mystical Deathly Hallows are uncovered, and Voldemort finds out about their mission, the biggest battle begins, and life as they know it will never be the same again.",
        "Language": "English, Latin",
        "Country": "United Kingdom, United States",
        "Awards": "Nominated for 3 Oscars. 46 wins & 94 nominations total",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "8.1/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "96%"
        }, {"Source": "Metacritic", "Value": "85/100"}],
        "Metascore": "85",
        "imdbRating": "8.1",
        "imdbVotes": "806,041",
        "imdbID": "tt1201607",
        "Type": "movie",
        "DVD": "11 Nov 2011",
        "BoxOffice": "$381,409,310",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    }, {
        "Title": "Se7en",
        "Year": "1995",
        "Rated": "R",
        "Released": "22 Sep 1995",
        "Runtime": "127 min",
        "Genre": "Crime, Drama, Mystery",
        "Director": "David Fincher",
        "Writer": "Andrew Kevin Walker",
        "Actors": "Morgan Freeman, Brad Pitt, Kevin Spacey",
        "Plot": "A film about two homicide detectives' (Morgan Freeman and Brad Pitt) desperate hunt for a serial killer who justifies his crimes as absolution for the world's ignorance of the Seven Deadly Sins. The movie takes us from the tortured remains of one victim to the next as the sociopathic \"John Doe\" (Kevin Spacey) sermonizes to Detectives Somerset and Mills -- one sin at a time. The sin of Gluttony comes first and the murderer's terrible capacity is graphically demonstrated in the dark and subdued tones characteristic of film noir. The seasoned and cultured but jaded Somerset researches the Seven Deadly Sins in an effort to understand the killer's modus operandi while the bright but green and impulsive Detective Mills (Pitt) scoffs at his efforts to get inside the mind of a killer...",
        "Language": "English",
        "Country": "United States",
        "Awards": "Nominated for 1 Oscar. 29 wins & 43 nominations total",
        "Poster": "https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "8.6/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "82%"
        }, {"Source": "Metacritic", "Value": "65/100"}],
        "Metascore": "65",
        "imdbRating": "8.6",
        "imdbVotes": "1,520,496",
        "imdbID": "tt0114369",
        "Type": "movie",
        "DVD": "19 Dec 2000",
        "BoxOffice": "$100,125,643",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    }, {
        "Title": "Fantastic Beasts and Where to Find Them",
        "Year": "2016",
        "Rated": "PG-13",
        "Released": "18 Nov 2016",
        "Runtime": "132 min",
        "Genre": "Adventure, Family, Fantasy",
        "Director": "David Yates",
        "Writer": "J.K. Rowling",
        "Actors": "Eddie Redmayne, Katherine Waterston, Alison Sudol",
        "Plot": "In mid-1920s New York, Newt Scamander, a British young activist wizard, arrives in the city, holding a mysterious leather suitcase that shelters diverse and magical creatures that exist among us. Amid an already fragile equilibrium of secrecy, and the increasing disasters ascribed to the dark wizard, Gellert Grindelwald, Newt's precious suitcase goes missing, and to make matters worse, several creatures manage to escape. Before long, this unforeseen complication catches Senior Auror Percival Graves' attention who targets Newt, against the backdrop of an invisible, devastating, and utterly unpredictable menace that still wreaks havoc on 5th Avenue. In the end, is there a hidden agenda behind Graves' intentions? Moreover, what will happen to the remaining fantastic beasts that are still on the loose?",
        "Language": "English, Central Khmer",
        "Country": "United Kingdom, United States",
        "Awards": "Won 1 Oscar. 15 wins & 54 nominations total",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMjMxOTM1OTI4MV5BMl5BanBnXkFtZTgwODE5OTYxMDI@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "7.3/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "74%"
        }, {"Source": "Metacritic", "Value": "66/100"}],
        "Metascore": "66",
        "imdbRating": "7.3",
        "imdbVotes": "429,936",
        "imdbID": "tt3183660",
        "Type": "movie",
        "DVD": "28 Mar 2017",
        "BoxOffice": "$234,037,575",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    }, {
        "Title": "Fantastic Beasts: The Crimes of Grindelwald",
        "Year": "2018",
        "Rated": "PG-13",
        "Released": "16 Nov 2018",
        "Runtime": "134 min",
        "Genre": "Adventure, Family, Fantasy",
        "Director": "David Yates",
        "Writer": "J.K. Rowling",
        "Actors": "Eddie Redmayne, Katherine Waterston, Dan Fogler",
        "Plot": "In an effort to thwart Grindelwald's plans of raising pure-blood wizards to rule over all non-magical beings, Albus Dumbledore enlists his former student Newt Scamander, who agrees to help, though he's unaware of the dangers that lie ahead. Lines are drawn as love and loyalty are tested, even among the truest friends and family, in an increasingly divided wizarding world.",
        "Language": "English, French",
        "Country": "United Kingdom, United States",
        "Awards": "3 wins & 23 nominations total",
        "Poster": "https://m.media-amazon.com/images/M/MV5BYWVlMDI5N2UtZTIyMC00NjZkLWI5Y2QtODM5NGE5MzA0NmVjXkEyXkFqcGdeQXVyNzU3NjUxMzE@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "6.5/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "36%"
        }, {"Source": "Metacritic", "Value": "52/100"}],
        "Metascore": "52",
        "imdbRating": "6.5",
        "imdbVotes": "239,843",
        "imdbID": "tt4123430",
        "Type": "movie",
        "DVD": "11 Mar 2019",
        "BoxOffice": "$159,555,901",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    },
    {
        "Title": "Star Wars: Episode III - Revenge of the Sith",
        "Year": "2005",
        "Rated": "PG-13",
        "Released": "19 May 2005",
        "Runtime": "140 min",
        "Genre": "Action, Adventure, Fantasy",
        "Director": "George Lucas",
        "Writer": "George Lucas",
        "Actors": "Hayden Christensen, Natalie Portman, Ewan McGregor",
        "Plot": "Three years into the Clone Wars, the Jedi rescue Palpatine from Count Dooku. As Obi-Wan pursues a new threat, Anakin acts as a double agent between the Jedi Council and Palpatine and is lured into a sinister plan to rule the galaxy.",
        "Language": "English",
        "Country": "United States",
        "Awards": "Nominated for 1 Oscar. 26 wins & 63 nominations total",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNTc4MTc3NTQ5OF5BMl5BanBnXkFtZTcwOTg0NjI4NA@@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "7.5/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "80%"
        }, {"Source": "Metacritic", "Value": "68/100"}],
        "Metascore": "68",
        "imdbRating": "7.5",
        "imdbVotes": "739,880",
        "imdbID": "tt0121766",
        "Type": "movie",
        "DVD": "01 Nov 2005",
        "BoxOffice": "$380,270,577",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    },
    {
        "Title": "Joker",
        "Year": "2019",
        "Rated": "R",
        "Released": "04 Oct 2019",
        "Runtime": "122 min",
        "Genre": "Crime, Drama, Thriller",
        "Director": "Todd Phillips",
        "Writer": "Todd Phillips, Scott Silver, Bob Kane",
        "Actors": "Joaquin Phoenix, Robert De Niro, Zazie Beetz",
        "Plot": "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.",
        "Language": "English",
        "Country": "United States, Canada",
        "Awards": "Won 2 Oscars. 118 wins & 239 nominations total",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "8.4/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "68%"
        }, {"Source": "Metacritic", "Value": "59/100"}],
        "Metascore": "59",
        "imdbRating": "8.4",
        "imdbVotes": "1,072,423",
        "imdbID": "tt7286456",
        "Type": "movie",
        "DVD": "03 Oct 2019",
        "BoxOffice": "$335,451,311",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    },
    {
        "Title": "The Conjuring",
        "Year": "2013",
        "Rated": "R",
        "Released": "19 Jul 2013",
        "Runtime": "112 min",
        "Genre": "Horror, Mystery, Thriller",
        "Director": "James Wan",
        "Writer": "Chad Hayes, Carey W. Hayes",
        "Actors": "Patrick Wilson, Vera Farmiga, Ron Livingston",
        "Plot": "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
        "Language": "English, Latin",
        "Country": "United States",
        "Awards": "15 wins & 22 nominations",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMTM3NjA1NDMyMV5BMl5BanBnXkFtZTcwMDQzNDMzOQ@@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "7.5/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "86%"
        }, {"Source": "Metacritic", "Value": "68/100"}],
        "Metascore": "68",
        "imdbRating": "7.5",
        "imdbVotes": "475,494",
        "imdbID": "tt1457767",
        "Type": "movie",
        "DVD": "22 Oct 2013",
        "BoxOffice": "$137,400,141",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    },
    {
        "Title": "Suicide Squad",
        "Year": "2016",
        "Rated": "PG-13",
        "Released": "05 Aug 2016",
        "Runtime": "123 min",
        "Genre": "Action, Adventure, Fantasy",
        "Director": "David Ayer",
        "Writer": "David Ayer, John Ostrander",
        "Actors": "Will Smith, Jared Leto, Margot Robbie",
        "Plot": "A secret government agency recruits some of the most dangerous incarcerated super-villains to form a defensive task force. Their first mission: save the world from the apocalypse.",
        "Language": "English, Japanese, Spanish",
        "Country": "United States",
        "Awards": "Won 1 Oscar. 17 wins & 40 nominations total",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMjM1OTMxNzUyM15BMl5BanBnXkFtZTgwNjYzMTIzOTE@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "5.9/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "26%"
        }, {"Source": "Metacritic", "Value": "40/100"}],
        "Metascore": "40",
        "imdbRating": "5.9",
        "imdbVotes": "652,660",
        "imdbID": "tt1386697",
        "Type": "movie",
        "DVD": "13 Dec 2016",
        "BoxOffice": "$325,100,054",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    },
    {
        "Title": "Split",
        "Year": "2016",
        "Rated": "PG-13",
        "Released": "20 Jan 2017",
        "Runtime": "117 min",
        "Genre": "Horror, Thriller",
        "Director": "M. Night Shyamalan",
        "Writer": "M. Night Shyamalan",
        "Actors": "James McAvoy, Anya Taylor-Joy, Haley Lu Richardson",
        "Plot": "Three girls are kidnapped by a man with a diagnosed 23 distinct personalities. They must try to escape before the apparent emergence of a frightful new 24th.",
        "Language": "English",
        "Country": "United States, Japan",
        "Awards": "10 wins & 25 nominations",
        "Poster": "https://m.media-amazon.com/images/M/MV5BZTJiNGM2NjItNDRiYy00ZjY0LTgwNTItZDBmZGRlODQ4YThkL2ltYWdlXkEyXkFqcGdeQXVyMjY5ODI4NDk@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "7.3/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "77%"
        }, {"Source": "Metacritic", "Value": "62/100"}],
        "Metascore": "62",
        "imdbRating": "7.3",
        "imdbVotes": "456,353",
        "imdbID": "tt4972582",
        "Type": "movie",
        "DVD": "18 Apr 2017",
        "BoxOffice": "$138,291,365",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    },
    {
        "Title": "Spider-Man: Far from Home",
        "Year": "2019",
        "Rated": "PG-13",
        "Released": "02 Jul 2019",
        "Runtime": "129 min",
        "Genre": "Action, Adventure, Sci-Fi",
        "Director": "Jon Watts",
        "Writer": "Chris McKenna, Erik Sommers, Stan Lee",
        "Actors": "Tom Holland, Samuel L. Jackson, Jake Gyllenhaal",
        "Plot": "Following the events of Avengers: Endgame (2019), Spider-Man must step up to take on new threats in a world that has changed forever.",
        "Language": "English, Italian, Czech",
        "Country": "United States",
        "Awards": "10 wins & 26 nominations",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMGZlNTY1ZWUtYTMzNC00ZjUyLWE0MjQtMTMxN2E3ODYxMWVmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "7.4/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "90%"
        }, {"Source": "Metacritic", "Value": "69/100"}],
        "Metascore": "69",
        "imdbRating": "7.4",
        "imdbVotes": "384,464",
        "imdbID": "tt6320628",
        "Type": "movie",
        "DVD": "27 Aug 2019",
        "BoxOffice": "$390,532,085",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    },
];



