export const novedades = [{
    "Title": "Fantastic Beasts: The Secrets of Dumbledore",
    "Year": "2022",
    "Rated": "N/A",
    "Released": "15 Apr 2022",
    "Runtime": "N/A",
    "Genre": "Adventure, Family, Fantasy",
    "Director": "David Yates",
    "Writer": "J.K. Rowling, Steve Kloves",
    "Actors": "Mads Mikkelsen, Ezra Miller, Jude Law",
    "Plot": "The third installment of the 'Fantastic Beasts and Where to Find Them' series which follows the adventures of Newt Scamander.",
    "Language": "English",
    "Country": "United States, United Kingdom",
    "Awards": "N/A",
    "Poster": "https://m.media-amazon.com/images/M/MV5BOTAzMTFlZTgtZDkxMi00MDQ1LTg5ZTUtMWQ3ZjVmN2E1Yjg5XkEyXkFqcGdeQXVyMTE1NDI5MDQx._V1_SX300.jpg",
    "Ratings": [],
    "Metascore": "N/A",
    "imdbRating": "N/A",
    "imdbVotes": "N/A",
    "imdbID": "tt4123432",
    "Type": "movie",
    "DVD": "N/A",
    "BoxOffice": "N/A",
    "Production": "N/A",
    "Website": "N/A",
    "Response": "True"
},
    {
        "Title": "Harry Potter and the Sorcerer's Stone",
        "Year": "2001",
        "Rated": "PG",
        "Released": "16 Nov 2001",
        "Runtime": "152 min",
        "Genre": "Adventure, Family, Fantasy",
        "Director": "Chris Columbus",
        "Writer": "J.K. Rowling, Steve Kloves",
        "Actors": "Daniel Radcliffe, Rupert Grint, Richard Harris",
        "Plot": "An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.",
        "Language": "English, Latin",
        "Country": "United Kingdom, United States",
        "Awards": "Nominated for 3 Oscars. 17 wins & 68 nominations total",
        "Poster": "https://m.media-amazon.com/images/M/MV5BNjQ3NWNlNmQtMTE5ZS00MDdmLTlkZjUtZTBlM2UxMGFiMTU3XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "7.6/10"}, {
            "Source": "Rotten Tomatoes",
            "Value": "81%"
        }, {"Source": "Metacritic", "Value": "64/100"}],
        "Metascore": "64",
        "imdbRating": "7.6",
        "imdbVotes": "702,733",
        "imdbID": "tt0241527",
        "Type": "movie",
        "DVD": "28 May 2002",
        "BoxOffice": "$318,087,620",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    },
    {
        "Title": "Thor: Love and Thunder",
        "Year": "2022",
        "Rated": "N/A",
        "Released": "08 Jul 2022",
        "Runtime": "N/A",
        "Genre": "Action, Adventure, Fantasy",
        "Director": "Taika Waititi",
        "Writer": "Stan Lee, Jennifer Kaytin Robinson, Taika Waititi",
        "Actors": "Taika Waititi, Matt Damon, Natalie Portman",
        "Plot": "The sequel to Thor: Ragnarok and the fourth movie in the Thor saga.",
        "Language": "English",
        "Country": "United States",
        "Awards": "N/A",
        "Poster": "https://m.media-amazon.com/images/M/MV5BMzZjMTIwNjYtYTg0ZS00ZDFjLTk3MDctMTY3ZTgwMjQ4MmFiXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SX300.jpg",
        "Ratings": [],
        "Metascore": "N/A",
        "imdbRating": "N/A",
        "imdbVotes": "N/A",
        "imdbID": "tt10648342",
        "Type": "movie",
        "DVD": "N/A",
        "BoxOffice": "N/A",
        "Production": "N/A",
        "Website": "N/A",
        "Response": "True"
    },
    {
        "Title": "The Mandalorian",
        "Year": "2019",
        "Rated": "TV-14",
        "Released": "12 Nov 2019",
        "Runtime": "40 min",
        "Genre": "Action, Adventure, Sci-Fi",
        "Director": "N/A",
        "Writer": "Jon Favreau",
        "Actors": "Pedro Pascal, Gina Carano, Giancarlo Esposito",
        "Plot": "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
        "Language": "English",
        "Country": "United States",
        "Awards": "Won 14 Primetime Emmys. 49 wins & 109 nominations total",
        "Poster": "https://m.media-amazon.com/images/M/MV5BZDhlMzY0ZGItZTcyNS00ZTAxLWIyMmYtZGQ2ODg5OWZiYmJkXkEyXkFqcGdeQXVyODkzNTgxMDg@._V1_SX300.jpg",
        "Ratings": [{"Source": "Internet Movie Database", "Value": "8.8/10"}],
        "Metascore": "N/A",
        "imdbRating": "8.8",
        "imdbVotes": "357,780",
        "imdbID": "tt8111088",
        "Type": "series",
        "totalSeasons": "3",
        "Response": "True"
    }];
